title: Default Page
preset: page
fields:
  mystructure:
    type: structure
    translate: false      # <-------     
    fields:
      text:
        type: textarea
      autoid:             # <-------
        type: autoid
        translate: false 
  builder:
    type: builder
    label: Builder
    fieldsets:
      text: auf_style/blueprints/builder/text
      link: auf_style/blueprints/builder/link
      container: auf_style/blueprints/builder/container
