title: Default Page
preset: page
fields:
  builder:
    type: builder
    label: Builder
    fieldsets:
      text: auf_style/blueprints/builder/text
      link: auf_style/blueprints/builder/link
      container: auf_style/blueprints/builder/container
