title: Site
tabs:
  #CONTENT-TAB
  content:
    sections:
      published:
        headline: Published
        type: pages
        status: listed
      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted
      drafts:
        headline: Drafts
        type: pages
        status: draft  
  #STYLES-TAB
  styles:
    fields:

      preview_urls:
        label: Preview Urls
        type: info
        text: >
          
          <a href="../style-boxes-preview" target="_blank">Style: Box/es Theme/s</a>
          <br>
          <a href="../style-tests" target="_blank">Style: Tests (Style Themes)</a>
          <br>
          <a href="../style-page-theme" target="_blank">Style: Page Theme</a>
          <br>
          <a href="../style-fluid-typography" target="_blank">Style: Fluid Typography</a>


      type_themes_divider:
        type: headline
        label: Type Themes
      
      type_themes:
        extends: auf_style/blueprints/fields/type_themes
      
      box_themes_divider:
        type: headline
        label: Box Themes
        
      box_themes:
        extends: auf_style/blueprints/fields/box_themes


      style_themes_divider:
        type: headline
        label: Style Themes

      color_themes:
        extends: auf_style/blueprints/fields/color_themes
      background_themes:
        extends: auf_style/blueprints/fields/background_themes
      border_themes:
        extends: auf_style/blueprints/fields/border_themes
      outline_themes:
        extends: auf_style/blueprints/fields/outline_themes
      text_shadow_themes:
        extends: auf_style/blueprints/fields/text_shadow_themes
      box_shadow_themes:
        extends: auf_style/blueprints/fields/box_shadow_themes
      
      

  #FILES-TAB
  files:
    fields:
      files:
        type: files
        label: Files