title: Site
tabs:
  #CONTENT-TAB
  content:
    sections:
      published:
        headline: Published
        type: pages
        status: listed
      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted
      drafts:
        headline: Drafts
        type: pages
        status: draft  
  #STYLES-TAB
  styles:
    label: Style Settings
    sections:
      style_settings: auf_style/site_style_settings

  #FILES-TAB
  files:
    fields:
      files:
        type: files
        label: Files