title: Site
fields:
  files:
    type: files
    label: Files

  color_themes:
    extends: auf_style/blueprints/fields/color_themes
  background_themes:
    extends: auf_style/blueprints/fields/background_themes
  border_themes:
    extends: auf_style/blueprints/fields/border_themes
  box_shadow_themes:
    extends: auf_style/blueprints/fields/box_shadow_themes
  
  box_themes:
    extends: auf_style/blueprints/fields/box_themes

  
    